MB.Presentation/Areas/Administrator/Pages/ArticleCategoryManagement/List.cshtml.cs
using MB.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class ListModel : PageModel
    {
        public List<ArticleCategoryViewModel> ArticleCategories { get; set; }
        private readonly IArticleCategoryApplication _categoryApplication;

        public ListModel(IArticleCategoryApplication categoryApplication)
        {
            _categoryApplication = categoryApplication;
        }

        public void OnGet()
        {
            ArticleCategories = _categoryApplication.list();
        }

        public RedirectToPageResult OnPostDelete(long id)
        {
            _categoryApplication.Delete(id);
            return RedirectToPage("./List");
        }
        public RedirectToPageResult OnPostActivate(long id)
        {
            _categoryApplication.Activate(id);
            return RedirectToPage("./List");
        }
    }
}

MB.Presentation/Areas/Administrator/Pages/ArticleManagement/List.cshtml.cs
using MB.Application.Contract.Article;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.Areas.Administrator.Pages.ArticleManagement
{
    public class ListModel : PageModel
    {
        private readonly IArticleApplication _articleApplication;
        public List<ArticleViewModel> Articles { get; set; }
        public ListModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            Articles = _articleApplication.GetList();
        }

        public RedirectToPageResult OnPostDelete(long id)
        {
            _articleApplication.Delete(id);
            return RedirectToPage("./List");
        }

        public RedirectToPageResult OnPostActivate(long id)
        {
            _articleApplication.Activate(id);
            return RedirectToPage("./List");
        }
    }
}

MB.Presentation/Areas/Administrator/Pages/CommentManagement/List.cshtml.cs
using MB.Application.Contract.Comment;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.Areas.Administrator.Pages.CommentManagement
{
    public class ListModel : PageModel
    {
        public List<CommentViewModel> Comments { get; set; }
        private readonly ICommentApplication _commentApplication;

        public ListModel(ICommentApplication commentApplication)
        {
            _commentApplication = commentApplication;
        }

        public void OnGet()
        {
            Comments = _commentApplication.GetComments();
        }

        public RedirectToPageResult OnPostAccept(long id)
        {
            _commentApplication.Confirmed(id);
            return RedirectToPage("./List");
        }

        public RedirectToPageResult OnPostReject(long id)
        {
            _commentApplication.Canceled(id);
            return RedirectToPage("./List");
        }
    }
}

MB.Presentation/Areas/Administrator/Pages/CommentManagement/List.cshtml
@page
@using MB.Domain.CommentAgg
@model MB.Presentation.Areas.Administrator.Pages.CommentManagement.ListModel
@{
}
<div class="card">
    <div class="card-header">
        <h3 class="float-left">Comment List</h3>
        
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Message</th>
                    <th>Article</th>
                    <th>Status</th>
                    <th>CreationDate</th>
                    @* <th>Edit</th> *@
                   @* <th>Delete</th>*@
                </tr>
            </thead>
            <tbody>
                @foreach (var comment in @Model.Comments)
                {
                    <tr>
                        <td>@comment.Id</td>
                        <td>@comment.Name</td>
                        <td>@comment.Email</td>
                        <td>@comment.Message</td>
                        <td>@comment.Article</td>

                        <td>
                            @if (comment.Status == Statuses.New)
                            {
                                <form method="post" asp-page-handler="Accept" class="float-left">
                                    <button class="btn btn-success">Accept</button>
                                    <input type="hidden" name="id" value="@comment.Id" />
                                </form>
                                <form method="post" asp-page-handler="Reject" class="float-left">
                                    <button class="btn btn-danger">Reject</button>
                                    <input type="hidden" name="id" value="@comment.Id" />
                                </form>
                            }else if (comment.Status==Statuses.Confirmed)
                            {
                                <i class="fa fa-check fa-2x text-success"></i>
                            }
                            else
                            {
                                <i class="fa fa-close fa-2x text-danger"></i>
                            }
                        </td>
                        <td>@comment.CreationDate</td>
                        <td>
                            @*<a class="btn btn-warning" asp-page="./Edit" asp-route-id="@comment.Id">Edit</a>*@

                        </td>
                        <td>
                           @* @if (article.IsDelete)
                            {
                                <form method="post" asp-page-handler="Activate" class="float-left">
                                    <button class="btn btn-success">Activate</button>
                                    <input type="hidden" name="id" value="@article.Id" />
                                </form>
                            }
                            else
                            {
                                <form method="post" asp-page-handler="Delete" class="float-left">
                                    <button class="btn btn-danger">Delete</button>
                                    <input type="hidden" name="id" value="@article.Id" />
                                </form>
                            }*@
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>